---
title: "STAT 692 Final Project: NYC Housing market price modeling by location"
author: "Riana Guha"
date: "Spring 2024"
output:
  html_document: 
    toc: yes
  pdf_document: default
urlcolor: cyan
---

# Introduction

The main aim of this project is to model the NYC housing data to determine the optimal house price. I will also be focusing on the house location and it's importance in the price.

Project objectives:
Price Analysis: find the ideal price range for houses using predictive modeling. This will provide insights for investors and real estate agents to make informed decisions before purchasing a house in NYC.

Location Analysis: Analyze the importance of house location (neighborhoods, districts, regions).

Key Features:
-`BROKERTITLE`: Title of the broker
-`TYPE`: Type of the house
-`PRICE`: Price of the house
-`BEDS`: Number of bedrooms
-`BATH`: Number of bathrooms
-`PROPERTYSQFT`: Square footage of the property
-`ADDRESS`: Full address of the house
-`STATE`: State of the house
-`MAIN_ADDRESS`: Main address information
-`ADMINISTRATIVE_AREA_LEVEL_2`: Administrative area level 2 information
-`LOCALITY`: Locality information
-`SUBLOCALITY`: Sublocality information
-`STREET_NAME`: Street name
-`LONG_NAME`: Long name
-`FORMATTED_ADDRESS`: Formatted address
-`LATITUDE`: Latitude coordinate of the house
-`LONGITUDE`: Longitude coordinate of the house

